package chronos.test.e2e;


import chronos.data.dto.*;
import chronos.data.factory.datafaker.*;
import chronos.page.*;
import chronos.test.BaseTest;
import io.qameta.allure.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static chronos.page.BasePage.clicar;
import static chronos.page.BasePage.clicarElementoXPATH;

public class EndToEndTest extends BaseTest {
    EdicaoPage edicaoPage = new EdicaoPage();
    EdicaoData edicaoData = new EdicaoData();
    LoginPage loginPage = new LoginPage();
    EtapaPage etapaPage = new EtapaPage();
    EtapaData etapaData = new EtapaData();
    LoginData loginData = new LoginData();
    TrilhaPage trilhaPage = new TrilhaPage();
    ModuloPage moduloPage = new ModuloPage();
    ModuloData moduloData = new ModuloData();
    EstagiarioPage estagiarioPage = new EstagiarioPage();
    EstagiarioData estagiarioData = new EstagiarioData();
    String nomeEdicaoCadastrada = "";

    private static final By EDICAO_ABA = By.cssSelector("a#link-edicoes");
    public static final By VINCULAR_TRILHA = By.cssSelector("div#root div:nth-child(6) > button");
    public static final By VINCULAR_TRILHA_SELECT = By.cssSelector("div#idTrilha");
    public static final By CONFIMAR_VINCULO = By.cssSelector("div#root form > div > button");
    private static final By BTN_ABA_TRILHAS = By.cssSelector("a#link-trilhas");
    private static final By BTN_ADICIONAR_TRILHA = By.cssSelector("#root > section > section > div.MuiBox-root.css-o2ea32 > button");

    public static final By CURRICULO_SELECT = By.cssSelector("div#select");
    public static final By DASHBOARD_EDICAO = By.cssSelector("div#select");
    public static final By VINCULAR_MODULO = By.cssSelector("div#root div.MuiTableContainer-root.css-7imslz > div > button");
    public static final By VINCULAR_MODULO_SELECT = By.cssSelector("div#idModulo");
    public static final By SELECT_CURRICULO_TRILHA = By.cssSelector("#select");
    public static final By CONFIRMAR_VINCULO_MODULO = By.cssSelector("div#root form > div > button");
    //@Test
    @Feature("EndToEnd - UI")
    @Story("Valida todo o fluxo da aplicação de ponta a ponta")
    @Description("Testa se o usuário consegue utilizar a aplicação como um todo.")
    @Severity(SeverityLevel.CRITICAL)
    public void testEndToEnd(){
        LoginDTO loginValido = loginData.loginDadosValidos();
        loginPage.fazerLogin(loginValido.getUsername(), loginValido.getSenha());
        EdicaoDTO edicaoACadastrar = edicaoData.edicaoDadosValidosEndToEnd();
        edicaoPage.cadastrarEdicao(edicaoACadastrar);
        nomeEdicaoCadastrada = edicaoACadastrar.getNome();
        clicarElementoXPATH(nomeEdicaoCadastrada);
        TrilhaCadastroDTO trilhaBack = TrilhaData.trilhaValidaBackEnd();
        TrilhaCadastroDTO trilhaFront = TrilhaData.trilhaValidaFrontEnd();
        TrilhaCadastroDTO trilhaQA = TrilhaData.trilhaValidaQA();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/trilhas");
        clicar(BTN_ADICIONAR_TRILHA);
        trilhaPage.cadastrarTrilhaComSucessoE2E(trilhaBack);
        clicar(BTN_ADICIONAR_TRILHA);
        trilhaPage.cadastrarTrilhaComSucessoE2E(trilhaFront);
        clicar(BTN_ADICIONAR_TRILHA);
        trilhaPage.cadastrarTrilhaComSucessoE2E(trilhaQA);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/modulos");
        ModuloDTO moduloDTOQA = moduloData.moduloQA();
        moduloPage.clicarBtnModuloAdicionar();
        moduloPage.preencherNome(moduloDTOQA.getNomeDoModulo());
        moduloPage.preencherLoginInstrutor(moduloDTOQA.getLoginDoInstrutorResponsavel());
        moduloPage.preencherConteudoProgramatico(moduloDTOQA.getConteudoProgramatico());
        moduloPage.clicarStatus();
        moduloPage.clicarAtivo();
        moduloPage.clicarSalvar();
        moduloPage.clicarSalvar();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/modulos");
        ModuloDTO moduloDTOFront = moduloData.moduloFrontEnd();
        moduloPage.clicarBtnModuloAdicionar();
        moduloPage.preencherNome(moduloDTOFront.getNomeDoModulo());
        moduloPage.preencherLoginInstrutor(moduloDTOFront.getLoginDoInstrutorResponsavel());
        moduloPage.preencherConteudoProgramatico(moduloDTOFront.getConteudoProgramatico());
        moduloPage.clicarStatus();
        moduloPage.clicarAtivo();
        moduloPage.clicarSalvar();
        moduloPage.clicarSalvar();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/modulos");
        ModuloDTO moduloDTOBack = moduloData.moduloBackEnd();
        moduloPage.clicarBtnModuloAdicionar();
        moduloPage.preencherNome(moduloDTOBack.getNomeDoModulo());
        moduloPage.preencherLoginInstrutor(moduloDTOBack.getLoginDoInstrutorResponsavel());
        moduloPage.preencherConteudoProgramatico(moduloDTOBack.getConteudoProgramatico());
        moduloPage.clicarStatus();
        moduloPage.clicarAtivo();
        moduloPage.clicarSalvar();
        moduloPage.clicarSalvar();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/trilhas");
        clicarElementoXPATH(trilhaFront.getNomeTrilha());
        clicar(VINCULAR_MODULO);
        clicar(VINCULAR_MODULO_SELECT);
        clicarElementoXPATH(moduloDTOFront.getNomeDoModulo());
        clicar(CONFIRMAR_VINCULO_MODULO);
        clicar(CONFIRMAR_VINCULO_MODULO);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/trilhas");
        clicarElementoXPATH(trilhaQA.getNomeTrilha());
        clicar(VINCULAR_MODULO);
        clicar(VINCULAR_MODULO_SELECT);
        clicarElementoXPATH(moduloDTOQA.getNomeDoModulo());
        clicar(CONFIRMAR_VINCULO_MODULO);
        clicar(CONFIRMAR_VINCULO_MODULO);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/trilhas");
        clicarElementoXPATH(trilhaBack.getNomeTrilha());
        clicar(VINCULAR_MODULO);
        clicar(VINCULAR_MODULO_SELECT);
        clicarElementoXPATH(moduloDTOBack.getNomeDoModulo());
        clicar(CONFIRMAR_VINCULO_MODULO);
        clicar(CONFIRMAR_VINCULO_MODULO);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/edicoes");
        clicarElementoXPATH(nomeEdicaoCadastrada);
        clicar(VINCULAR_TRILHA);
        clicar(VINCULAR_TRILHA_SELECT);
        clicarElementoXPATH(trilhaBack.getNomeTrilha());
        clicar(CONFIMAR_VINCULO);
        clicar(CONFIMAR_VINCULO);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/edicoes");
        clicarElementoXPATH(nomeEdicaoCadastrada);
        clicar(VINCULAR_TRILHA);
        clicar(VINCULAR_TRILHA_SELECT);
        clicarElementoXPATH(trilhaFront.getNomeTrilha());
        clicar(CONFIMAR_VINCULO);
        clicar(CONFIMAR_VINCULO);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/edicoes");
        clicarElementoXPATH(nomeEdicaoCadastrada);
        clicar(VINCULAR_TRILHA);
        clicar(VINCULAR_TRILHA_SELECT);
        clicarElementoXPATH(trilhaQA.getNomeTrilha());
        clicar(CONFIMAR_VINCULO);
        clicar(CONFIMAR_VINCULO);
        EstagiarioDTO estagiarioACriar1 = estagiarioData.estagiarioDadosValidos();
        EstagiarioDTO estagiarioACriar2 = estagiarioData.estagiarioDadosValidos();
        EstagiarioDTO estagiarioACriar3 = estagiarioData.estagiarioDadosValidos();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/estagiarios");
        estagiarioPage.cadastrarEstagiarioE2E(estagiarioACriar1, trilhaFront, edicaoACadastrar);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/estagiarios");
        estagiarioPage.cadastrarEstagiarioE2E(estagiarioACriar2, trilhaBack, edicaoACadastrar);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/estagiarios");
        estagiarioPage.cadastrarEstagiarioE2E(estagiarioACriar3, trilhaQA, edicaoACadastrar);
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/curriculos");
        clicar(SELECT_CURRICULO_TRILHA);
        clicarElementoXPATH(trilhaFront.getNomeTrilha());
        BasePage.selecionarCurriculo();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/curriculos");
        clicar(SELECT_CURRICULO_TRILHA);
        clicarElementoXPATH(trilhaBack.getNomeTrilha());
        BasePage.selecionarCurriculo();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/curriculos");
        BasePage.selecionarCurriculo();
        BasePage.irParaUrl("https://chronos-front-one.vercel.app/dashboard");
    };
}
